### ISSUE TITLE
Register with one character

### ISSUE THREAD

**Issue by ehsan-afsharnia** [Lo-Agency-Internship/samira-shabnam-khashayar-workout-tracker#26]
When the user registers, he can enter with one character.

**Comment by Khashiiiiiii** [comment]
> When the user registers, he can enter with one character.


Imagine today is 06/28 and i added a task in 06/21. Ok , everything in filter buttons are true but for due date no.

bug2

Offer : u can filter tasks in frontend . U just send one time informations to frontend and use them everywhere u want.

Thanks for your review.
We have been informed about this issue before, thus I will close this issue and we'll try to fix it ASAP.
