### ISSUE TITLE
Clear codes of too much comment and console log

### ISSUE THREAD

**Issue by ShadiNrz** [Lo-Agency-Internship/samira-shabnam-khashayar-workout-tracker#30]
in index.js file there are too much comments and also console log that should be clear

**Comment by Khashiiiiiii** [comment]
Thanks for your review.
About the comments you mentioned, a huge part of those comments are APIs related to having connection with other gyms. Thus we can't delete them unfortunately. About the console logs, they indicate the states of our database and in my opinion they are necessary.
