### ISSUE TITLE
Close button in modal does not work

### ISSUE THREAD

**Issue by ehsan-afsharnia** [Lo-Agency-Internship/samira-shabnam-khashayar-workout-tracker#32]
When the user clicks on the preview button, the modal opens, But to close the modal, you have to click the exit
 because the close button does not work.

**Comment by Khashiiiiiii** [comment]
> When the user clicks on the preview button, the modal opens, But to close the modal, you have to click the exit because the close button does not work.

Thank you for your review. We will fix it as soon as possible.
