### ISSUE TITLE
Too many comment codes

### ISSUE THREAD

**Issue by hutan88** [Lo-Agency-Internship/samira-shabnam-khashayar-workout-tracker#38]
In index.js file from line 121 to 187 has  too many code commented.

**Comment by Khashiiiiiii** [comment]
> In index.js file from line 121 to 187 has too many code commented.

Thanks for your review.
About the comments you mentioned, a huge part of those comments are APIs related to having connection with other gyms. Thus we can't delete them unfortunately.
