### ISSUE TITLE
Filtering bug

### ISSUE THREAD

**Issue by mhmdrezanaderi** [Lo-Agency-Internship/samira-shabnam-khashayar-workout-tracker#39]
Imagine today is 06/28 and i added a task in 06/21.
Ok , everything in filter buttons are true but for due date no.

![bug2](https://user-images.githubusercontent.com/88972370/176137259-da519569-7705-4c2c-9f0c-9237ee424ed5.png)

**Offer** : u can filter tasks in frontend .
U just send one time informations to frontend and use them everywhere u want.

**Comment by Khashiiiiiii** [comment]
> Imagine today is 06/28 and i added a task in 06/21. Ok , everything in filter buttons are true but for due date no.
> 
> ![bug2](https://user-images.githubusercontent.com/88972370/176137259-da519569-7705-4c2c-9f0c-9237ee424ed5.png)
> 
> **Offer** : u can filter tasks in frontend . U just send one time informations to frontend and use them everywhere u want.

Thanks for your review. 
We have been informed about this issue before, thus I will close this issue and we'll try to fix it ASAP.
