### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by Helia-nik** [Lo-Agency-Internship/samira-shabnam-khashayar-workout-tracker#40]
footer bayad be payine safhe bechasbe, injuri ke alan hast kheyli moshkel dare va nabudanesh behtare az nazare man.

**Comment by Khashiiiiiii** [comment]
Thanks for your review
We'll fix this issue as soon as possible.

**Comment by Khashiiiiiii** [comment]
> footer bayad be payine safhe bechasbe, injuri ke alan hast kheyli moshkel dare va nabudanesh behtare az nazare man.

Thanks for your review
We'll fix this issue as soon as possible.
