### ISSUE TITLE
signup form ui

### ISSUE THREAD

**Issue by Helia-nik** [Lo-Agency-Internship/samira-shabnam-khashayar-workout-tracker#41]
forme signup aslan ui khubi nadare, va hatta center nist, asan karbar moshtagh be register nemishe hatta.

**Comment by Khashiiiiiii** [comment]
> forme signup aslan ui khubi nadare, va hatta center nist, asan karbar moshtagh be register nemishe hatta.

Thanks for your review
We'll fix this issue as soon as possible.
